### PR TITLE
Fixing label issues on cropping image

### LINKED ISSUE #5309: Alt text / labeling issues in image cropping UI
### Issue Summary

Related: #5291. Spotted while reviewing #5292. There are three accessibility issues picked up by Axe in the image cropping UI:

image-cropping

- jcrop generates its own `img` element. That element does not even have an alt text, so the image `src` is read out loud.
- The image tag rendered server-side uses the 
`title` attribute for the alt text. While this might be appropriate on the site’s front-end, here the image is displayed in the admin, to be edited, so the `title` text does not work as an `alt` in that context. Relevant code: https://github.com/wagtail/wagtail/blob/70a749b10a1b0c4dac527da28e54cbb3581a774e/wagtail/images/templates/wagtailimages/images/edit.html#L67
- jcrop injects its own `radio` element, which is flagged as not having a label

### Steps to Reproduce

1. Go to the image editing UI on any Wagtail admin, `/admin/images/52/`
2. Navigate to the cropping UI with a screen reader

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Wagtail version: v2.6a0

---

I think the simplest solution for this would be to make sure the image created with jcrop has an empty `alt=""` attribute, and same for our server-generated image. This might need further consideration for us to design a more screen-reader-friendly solution.

### PR DESCRIPTION
**Pull request by Luzzzi**
Fix #5309 

In the inspector, going into the DOM, we see the appearance of the label and its relationship with the input tag

This is a proposal to add a label tag for the input tag created by jcrop and add a name attribute on this input tag. 
I have hesitated between vanillajs and JQuery, please let me know if you want more homogeneity.

_________________________________________________________________________________________________________________________________
- [x] Do the tests still pass?[^1]
- [x] Does the code comply with the style guide? 
    - [x] Run `make lint` from the Wagtail root. 
- [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
- [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    - [x] **Please list the exact browser and operating system versions you tested**: Google Chrome / Linux Ubuntu
    - [ ] **Please list which assistive technologies [^3] you tested**: 
- [ ] For new features: Has the documentation been updated accordingly?

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

**Comment by PaarthAgarwal** [comment]
Hey @Luzzzi. Which node version are you on?

**Comment by Luzzzi** [comment]
Hi @PaarthAgarwal ! Thanks for your help, I resolve my issue with _lint_ myself this week-end. For information : I tried to run the `make lint` command in my local environnement but I used docker so it doesn't work.

**Comment by PaarthAgarwal** [comment]
Happy to hear.

File: wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js [hunk 1]
```diff
@@ -30,6 +30,20 @@ function setupJcrop(image, original, focalPointOriginal, fields) {
       // Set alt="" on the image so its src is not read out loud to screen reader users.
       var $holderImage = $('img', jcropapi.ui.holder);
       $holderImage.attr('alt', '');
+
+      // Create a label tag for the input for accessibility.
+      const label = document.createElement('label');
+
+      label.setAttribute('for', 'jcrop');
+      label.classList.add('className', 'visuallyhidden');
+      label.innerHTML = 'Cropping Tool';
```
Comment (lb-) [inline wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js:39]: Are we able to use the JavaScript translation system here, it would be good to have this translatable.

Also it should probably be lower case 'tool' so 'Cropping tool'.

**Review by lb- — CHANGES_REQUESTED** [review]

**Comment by lb-** [comment]
@Luzzzi  thanks for taking the time to put through your first PR to wagtail, I have a small bit of feedback, overall this looks good though.

I have not tested locally yet.

File: wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js (hunk 1 above)
Comment (lb-) [reply wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js:39]: You can use `window.getText` for this - search through the code for `getText` to see usage.

See https://docs.djangoproject.com/en/4.0/topics/i18n/translation/#internationalization-in-javascript-code for more information in the Django docs for what this is / how it works.

File: wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js [hunk 2]
```diff
@@ -30,6 +30,20 @@ function setupJcrop(image, original, focalPointOriginal, fields) {
       // Set alt="" on the image so its src is not read out loud to screen reader users.
       var $holderImage = $('img', jcropapi.ui.holder);
       $holderImage.attr('alt', '');
+
+      // Create a label tag for the input for accessibility.
+      const label = document.createElement('label');
+
+      label.setAttribute('for', 'jcrop');
```
Comment (lb-) [inline wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js:37]: This will not work as expected, `for` must reference an element by its `id` not by its `name`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for

You will likely need to put an id on the input element that gets generated also, alternatively you can wrap the input with the label element like this
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#simple_label_example

And just put the label content inside a span and put the visuallyhidden class on that span.

`aria-label` on the `input` itself may be suitable here though https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

File: wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js [hunk 3]
```diff
@@ -30,6 +30,20 @@ function setupJcrop(image, original, focalPointOriginal, fields) {
...
+      label.classList.add('className', 'visuallyhidden');
+      label.innerHTML = 'Cropping Tool';
+
+      var holder = document.getElementsByClassName('jcrop-holder');
+      holder[0].appendChild(label);
+
+      // Set the name attribut on the input corresponding to the label.
+      var $holderInput = $('input', jcropapi.ui.holder);
```
Comment (lb-) [inline wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js:45]: as above, the name will not be suitable.
Also - adjusting the name may cause some odd issues for form submission.

File: wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js [hunk 4]
```diff
@@ -30,6 +30,20 @@ function setupJcrop(image, original, focalPointOriginal, fields) {
...
+      const label = document.createElement('label');
+
+      label.setAttribute('for', 'jcrop');
+      label.classList.add('className', 'visuallyhidden');
+      label.innerHTML = 'Cropping Tool';
+
+      var holder = document.getElementsByClassName('jcrop-holder');
+      holder[0].appendChild(label);
+
+      // Set the name attribut on the input corresponding to the label.
```
Comment (lb-) [inline wagtail/images/static_src/wagtailimages/js/focal-point-chooser.js:44]: small typo here, `attribute` missing the `e`

**Review by lb- — APPROVED** [review]
@Luzzzi  thanks so much for this original PR, I have made a few tweaks to get this over the line.

Congrats on your first PR into Wagtail.

I have added you as `Lucie Le Frapper` to the contributors list, please let me know if you want the name listed.

Revisions made
- add a unique `id` instead of a `name` to the input and use that for the label's `for` attribute
- pass in a translated value in the HTML template via a data attribute so that we can provide a translated label for this
- remove the accidental `className` class (yeah, switching from React to normal HTML is a bit tricky, I have done this kind of thing many times).

### Screenshots

**without fix - axe**

Screen Shot 2022-06-10 at 7 54 53 am

**with fix - axe**

Screen Shot 2022-06-10 at 7 54 38 am

**voiceover validation**


Screen Shot 2022-06-10 at 8 05 35 am
