### PR TITLE
Fix WebP/AVIF/HEIC image preview placeholder

### LINKED ISSUE #10947: WebP image upload preview fails
### Issue Summary

When using the image upload page in the admin interface, WebP images are not rendered as a preview while the image file is being uploaded, or once the file has completed upload.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject` as per the [Quick Install](https://docs.wagtail.org/en/stable/getting_started/quick_install.html#install-wagtail);
2. Download https://www.gstatic.com/webp/gallery/1.jpg and https://www.gstatic.com/webp/gallery/1.webp into a convenient location (other JPG and WEBP files can be substituted);
3. Browse to the new Wagtail installation, log in and navigate to the _Images_ page, and then the _Add an Image_ page;
4. Upload 1.jpg, either via drag-and-drop or selecting an image file. Observe that the image appears almost immediately at the left with an upload progress bar. Once uploaded the image remains and a form is presented allowing attributes of the image to be adjusted;
5. Upload 1.webp. Observe that the image does not appear at the left, but the progress bar does. Once uploaded the image still does not appear but the form is presented allowing attributes of the image to be adjusted;
6. Observe that nothing is logged in the browser console;
7. Return to the image gallery and observe that the images have both been uploaded.

_Note: it will be necessary to use a rate limiter in responsive design mode within the browser dev tools to see the progress bar, as I've done in the demonstration below._

https://github.com/wagtail/wagtail/assets/1977376/b4fd51ac-4a7e-46bc-9157-8bf5f3bd1c42

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

During the upload of the WebP image, the image preview should appear on the left, like it does for the JPG image.

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: **yes**

Note: I have also observed the same issue when uploading _some_ SVG images. I will add to this issue if/when I find example images I can share.

### Technical details

- Python version: 3.10.4
- Django version: 4.2.5.
- Wagtail version: 5.1.2.
- Browser versions:
  -  Firefox 114.0.2, Chrome 117.0.5938.92, Safari 16.5 (18615.2.9.11.4), all on Mac with Apple M1, Ventura 13.4
  -  Firefox 112.0.2, Chrome 117.0.5938.92, Safari 16.2 (18614.3.7.1.5), all on Mac with x86, Ventura 13.1
  -  _Sorry, I don't have ready access to a Windows machine anymore._

### PR DESCRIPTION
**Pull request by Coll76**
## Summary

Fixes #10947 - The WebP, AVIF, and HEIC images now display a placeholder icon during upload when browser canvas preview generation fails.

## Changes

- Modified `wagtail/images/static_src/wagtailimages/js/add-multiple.js`:
  - Changed `.remove()` to `.hide()` for the placeholder icon (line 29)
  - Added logic in `done` callback to show placeholder icon when no canvas preview is generated (lines 138-141)

## Why

The jQuery File Upload library generates canvas previews for supported formats (JPG, PNG, GIF), but fails silently for newer formats (WebP, AVIF, HEIC). The previous implementation permanently removed the placeholder icon, resulting in blank space when preview generation failed.

## Solution

Instead of removing the icon, we now hide it temporarily. If no canvas preview is generated by the time the upload completes, we show the placeholder icon again. This provides visual feedback that an image was uploaded successfully, even when browser-based preview generation is not supported.

## Testing

Based on the issue discussion:
- WebP images should now display placeholder icon instead of blank space
- AVIF images should now display placeholder icon instead of blank space
- HEIC images should now display placeholder icon instead of blank space
- JPG/PNG images should continue to display canvas preview (existing behavior preserved)

Fixes #10947

### CODE REVIEW

File: wagtail/images/static_src/wagtailimages/js/add-multiple.js [hunk 1]
```diff
@@ -133,6 +133,11 @@ $(function () {
 
     done: function (e, data) {
       var itemElement = $(data.context);
+
+      var thumb = itemElement.find('.preview .thumb');
+      if (thumb.find('canvas').length === 0) {
+        thumb.find('.icon').show();
+      }
```
Comment (thibaudcolas) [inline wagtail/images/static_src/wagtailimages/js/add-multiple.js]: It seems like we could have this logic directly in the `add` function, since we already know whether the preview is defined there? That’d be much simpler, and have the added benefit to show the thumbnail right away instead of only on completion.
