### PR TITLE
Auto-select single block in StreamField

### LINKED ISSUE #3998: Auto-select default block when there is only one option in StreamField
### Issue Summary

A `StreamField` with only one block looks like this:
image

Instead, the default block should be selected automatically the same way it happens when removing all content and pressing the (+) button.

This issue leads to bad user experience. 

### Steps to Reproduce

A `StreamField` with only one block.

### Technical details

* Wagtail version: 1.13

### PR DESCRIPTION
**Pull request by SebCorbin**
Fixes #3998

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

File: client/src/components/StreamField/blocks/StreamBlock.js [hunk 1]
```diff
@@ -85,6 +85,35 @@ class StreamBlockMenu extends BaseInsertionControl {
     $(placeholder).replaceWith(dom);
     this.element = dom.get(0);
     this.addButton = dom.find('button');
+
```
Comment (lb-) [inline client/src/components/StreamField/blocks/StreamBlock.js:88]: @SebCorbin it would be great to see a unit test for this behaviour if you can.

client/src/components/StreamField/blocks/StreamBlock.test.js

**Review by lb- — CHANGES_REQUESTED** [review]

File: client/src/components/StreamField/blocks/StreamBlock.js (hunk 1 above)
Comment (lb-) [reply client/src/components/StreamField/blocks/StreamBlock.js:88]: Thanks. Tests have been added.

File: client/src/components/StreamField/blocks/StreamBlock.js [hunk 2]
```diff
@@ -105,29 +134,11 @@ class StreamBlockMenu extends BaseInsertionControl {
...
-          icon: blockDef.meta.icon,
-        }));
-
-      return {
-        label: group || '',
-        type: group || '',
-        items: groupItems,
-      };
-    });
-
```
Comment (lb-) [inline client/src/components/StreamField/blocks/StreamBlock.js:125]: I think it might be nicer to pull this out to a getter or method on its own, it means we may process this data twice but makes the diffs easier to follow and avoids any unexpected changes to the delayed generation of these items.

Something like this...

```js

  get blockItems() {
    return this.groupedChildBlockDefs.map(([group, blockDefs]) => {
      const groupItems = blockDefs
        // Allow adding all blockDefs even when disabled, so validation only impedes when saving.
        // Keeping the previous filtering here for future reference.
        // .filter((blockDef) => !this.disabledBlockTypes.has(blockDef.name))
        .map((blockDef) => ({
          type: blockDef.name,
          label: blockDef.meta.label,
          icon: blockDef.meta.icon,
        }));

      return {
        label: group || '',
        type: group || '',
        items: groupItems,
      };
    });
  }

  renderMenu() {
    ReactDOM.render(
      <ComboBox
        label={comboBoxLabel}
        placeholder={comboBoxLabel}
        items={this.blockItems}
        getItemLabel={(type, item) => item.label}
        getItemDescription={(item) => item.label}
        getSearchFields={(item) => [item.label, item.type]}
        noResultsText={comboBoxNoResults}
        onSelect={this.onSelectBlock.bind(this)}
      />,
      this.combobox,
    );
  }
```

**Review by lb- — APPROVED** [review]
This works great, thank you.

I have made that small suggested change, rebased & will merge.
