### PR TITLE
Fix content path links in usage view to scroll to the correct element

### LINKED ISSUE #12014: HREF with reference.content_path in UsageView doesn't do anything
### Issue Summary
In the UsageView for a Page or Snippet, the Field column displays a list of fields containing a reference to that object. In [references_cell.html](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/tables/references_cell.html), each reference is wrapped in a link to that object's edit view, appended with `#content-path-{{ reference.content_path }}`. This appears to be meant as a way to jump to that specific field when opening the edit page, but no such ids are present on the elements and so they don't do anything - each link just opens the edit page from the top content, as usual.

### Steps to Reproduce

1. From the edit view for a Page or Snippet, click on the "i" Status icon in the top right and then go to the Usage page (provided there is at least one occurrence)
image
2. From the Usage page, click any example under the field column to go to the edit page for that item.
image
3. The url for the edit page will end in something like `edit/#content-path-body_streamfield.85af2509-0a67-4848-9808-b5f432492258`, but no such id exists on the page.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project:
    - Yes. Confirmed on a new install of Bakery demo.

### Technical details

-   Python version: **3.11.3**
-   Django version: **5.0.3**
-   Wagtail version: **6.1.2**
-   Browser version: **Chrome on Mac v125.0.6422.142**

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

### PR DESCRIPTION
**Pull request by laymonage**
Fixes #12014, and a few other scrolling-related issues.

https://github.com/wagtail/wagtail/assets/6379424/1a0f33d7-7180-412a-b223-9760a7cf57db

### CODE REVIEW

File: client/src/includes/panels.ts [hunk 1]
```diff
@@ -105,12 +107,18 @@ export function initCollapsiblePanels(
...
-  if (anchorTarget) {
-    anchorTarget.scrollIntoView({ behavior: 'smooth' });
+  const target = anchorTarget?.matches('[data-panel]')
+    ? anchorTarget
+    : getElementByContentPath();
+
+  if (target) {
+    setTimeout(() => {
+      target.scrollIntoView({ behavior: 'smooth' });
+    }, 100);
```
Comment (laymonage) [inline client/src/includes/panels.ts:122]: Feel free to experiment. I tried using no timeout at all and using a smaller value, but they didn't work. It seems `100` works consistently enough.

Try the following scenarios:

- Using the built-in "link" anchor feature
- Using the `contentpath` directive. Find an element with `data-contentpath` that you want to scroll to, which may or may not have the built-in anchor feature e.g. in `MultiFieldPanel`s and `StructBlock`s. Examples:
  - Block inside `StructBlock`, no built-in anchor: http://localhost:8000/admin/pages/82/edit/#:w:contentpath=e0b41ad1-cae5-482d-ae31-f13b35f17830.difficulty 
  - `StructBlock` itself, has built-in anchor: http://localhost:8000/admin/pages/82/edit/#:w:contentpath=e0b41ad1-cae5-482d-ae31-f13b35f17830
  - `FieldPanel` inside `MultiFieldPanel`, no built-in anchor: http://localhost:8000/admin/pages/82/edit/#:w:contentpath=recipe_headline
  - Top-level `FieldPanel`, has built-in anchor: http://localhost:8000/admin/pages/82/edit/#:w:contentpath=subtitle

Note that in some cases when using the `contentpath` directive, the browser may scroll directly to the input field and the label isn't visible. This is most noticeable in the top-levle `FieldPanel` case. This is because for some cases the label is within the element with `data-contentpath`, while in other cases it is outside. We could in theory try to find the label by traversing the ancestors/descendants and scroll to that element instead, but if we're not careful we may end up scrolling to the "parent" content instead of the most specific node.


Also, I recommend testing with recipe pages on bakery demo _but_ with the panels set on the Promote tab instead of the content tab, to ensure this all still works when the target element is in a tab that's not the first one. You can do this easily by changing `content_panels = Page.content_panels + [` to `promote_panels = Page.promote_panels + [`.

File: client/src/includes/tabs.js [hunk 2]
```diff
@@ -152,13 +153,6 @@ class Tabs {
       tabContent.hidden = false;
     }
 
-    if (this.state.initialPageLoad) {
-      // On first load set the scroll to top to avoid scrolling to active section and header covering up tabs
-      setTimeout(() => {
-        window.scrollTo(0, 0);
-      }, this.state.transition * 2);
-    }
-
```
Comment (laymonage) [inline client/src/includes/tabs.js:161]: As we discussed today, this doesn't do anything and may actually interfere with our scroll to anchor functionality. See commit message for details.

File: client/src/includes/tabs.js [hunk 3]
```diff
@@ -277,10 +271,11 @@ class Tabs {
 
   selectTabByURLHash() {
     if (window.location.hash) {
-      const cleanedHash = window.location.hash.replace(/[^\w\-#]/g, '');
```
Comment (laymonage) [inline client/src/includes/tabs.js:280]: I don't see a reason why we had to "clean" the hash, i.e. allowing only alphanumeric characters, dashes, and the `#` sign itself. This means the feature doesn't work if the anchored element has an `_`. AFAIK the browser's built-in scroll-to-anchor feature doesn't pose this limitation, so I decided to remove it.

File: client/src/includes/tabs.js [hunk 4]
```diff
@@ -277,10 +271,11 @@ class Tabs {
...
+      const anchorId = window.location.hash.slice(1);
+      const anchoredElement =
+        document.getElementById(anchorId) || getElementByContentPath();
       // Support linking straight to a tab, or to an element within a tab.
-      const tabID = document
-        .querySelector(cleanedHash)
```
Comment (laymonage) [inline client/src/includes/tabs.js:283]: Using `querySelector` would crash the editor if the hash begins with a number.

File: wagtail/admin/templates/wagtailadmin/tables/references_cell.html [hunk 5]
```diff
@@ -3,7 +3,7 @@
         {% for reference in value %}
             <li>
                 {% if edit_url %}
-                    <a href="{{ edit_url }}#content-path-{{ reference.content_path }}">
+                    <a href="{{ edit_url }}#:w:contentpath={{ reference.content_path }}">
```
Comment (laymonage) [inline wagtail/admin/templates/wagtailadmin/tables/references_cell.html:6]: using `contentpath` instead of `content-path` to match `data-contentpath`, but can be convinced otherwise.

File: client/src/utils/contentPath.ts [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+ * // with an URL e.g. https://example.com/#:w:contentpath=abc1.d2e.3f
+ * // returns <div data-contentpath="3f">...</div>
+ */
+export function getElementByContentPath(contentPath?: string) {
+  const path =
+    contentPath ||
+    new URLSearchParams(getWagtailDirectives()).get('contentpath');
+
+  return path
+    ? document.querySelector<HTMLElement>(getContentPathSelector(path))
```
Comment (thibaudcolas) [inline client/src/utils/contentPath.ts:76]: Seems like a generic type parameter would be useful here, but we can get there when we need it.

```suggestion
export function getElementByContentPath<T extends HTMLElement>(contentPath?: string) {
  const path =
    contentPath ||
    new URLSearchParams(getWagtailDirectives()).get('contentpath');

  return path
    ? document.querySelector<T>(getContentPathSelector(path))
```

**Review by thibaudcolas — APPROVED** [review]
Thank you, all working well across browsers! I think there is some room for more reliability than `setTimeout` but this is clearly better than what we had in place before.
