### PR TITLE
Fix TableBlock intialisation

### LINKED ISSUE #9107: Grid from TableBlock is missing after saving a page (from wagtail.contrib.table_block.blocks import TableBlock)
### Issue Summary

I imported the default TableBlock of the wagtail.contrib.table_block.blocks. After importing i used the TableBlock to display some content in a table. The TableBlock is initially working fine but after saving the grid is missing, to change some saved data maybe fix a typo or something.

Before saving:
image

After saving:
image

### Error Message

No error message

### Steps to Reproduce

Steps to Reproduce:

Setup a fresh wagtail instance.

Import TableBlock for creating a table as content. This import statement was being used "from wagtail.contrib.table_block.blocks import TableBlock" to import the TableBlock for a page model content.

Now we should be able to pick TableBlock as content for our content page.

After adding some content to the selected Table save the page as preview.

After saving and reopening the page to edit some content i can't see the grid from the table, as shown in the second screenshot.

Install Wagtail with all the libraries in techincal details

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

    Django>=4.0,<4.1
    wagtail>3
    wagtail_localize==1.2.1
    django-extensions==3.2.0
    psycopg2==2.9.3
    loglevel==0.1.2
    Wand==0.6.10

Thank you very much in advance.

I look forward to your feedback.

### PR DESCRIPTION
**Pull request by zerolab**
- move Handsontable render after load
- stops firing a resize event
- adjusts targets to account for the changed markup

Fixes #9107

https://www.loom.com/share/a1fdadcb119145ac9fa7938154b60229

### CODE REVIEW

**Comment by zerolab** [comment]
Note that I would argue this need backporting to 4.1 and 4.2

File: client/src/entrypoints/contrib/table_block/table.js [hunk 1]
```diff
@@ -173,15 +170,11 @@ function initTable(id, tableOptions) {
...
-  if ('resize' in $(window)) {
+  window.addEventListener('load', () => {
+    // Render the table. Calling render also removes 'null' literals from empty cells.
+    hot.render();
     resizeHeight(getHeight());
-    $(window).on('load', () => {
-      $(window).trigger('resize');
-    });
-  }
+  });
```
Comment (lb-) [inline client/src/entrypoints/contrib/table_block/table.js:177]:
```suggestion
    resizeWidth(getWidth());
  });
```

This also needed resize width on load, the width was not correct if the viewport was less than ~900px.

I will add this change, the rest looks good - thanks @zerolab !

**Review by lb- — APPROVED** [review]

**Comment by lb-** [comment]
* 4.2 stable - bb0b92c951f5c0164ccb4e050faf7a08d761c3a5
* 4.1 stable - b1028e862c8c9112f9f53bba2ad375a70765c7d6
