### PR TITLE
Fix duplicate block ids when duplicating stream blocks in page editor

### LINKED ISSUE #7712: Duplicate streamfield block duplicates UUID
### Issue Summary
I noticed streamfield's  blocks uuid can be not unique. 

It can be an issue, in my case in a headless setup, I cache blocks based on their UUIDs.

### Steps to Reproduce
For example, let's consider a streamfield, containing a structblock, containing a streamblock.
Duplicating an instance of this structblock, with existing streamblocks, cause the nested streamblock UUIDs to remain identical to the original ones

I created an example repo here https://github.com/fabienheureux/wagtail-duplicate-streamfield-uuid

1. `git clone https://github.com/fabienheureux/wagtail-duplicate-streamfield-uuid`
2. `./manage.py runserver`
3. `./manage.py shell`
4. `from home.models import HomePage`
5. `print(HomePage.objects.first().blocks.raw_data)`

```json
[
   {
      "type":"simple_question",
      "value":{
         "extended_answer":{
            "body":[
               {
                  "type":"text",
                  "value":"<p data-block-key=\"a7uom\">Test 1 2 1 2</p>",
                  "id":"ff7f1a7a-42a6-46c9-915c-5ca453b23698" 
               }
            ]
         }
      },
      "id":"520971d8-3d49-4779-b833-46222fdd48e1"
   },
   {
      "type":"simple_question",
      "value":{
         "extended_answer":{
            "body":[
               {
                  "type":"text",
                  "value":"<p data-block-key=\"a7uom\">Coucou</p>",
                  "id":"ff7f1a7a-42a6-46c9-915c-5ca453b23698"
               }
            ]
         }
      },
      "id":"ec72605c-b58a-4d57-9ead-2af3196575b4"
   }
]
```
➡️ The body's UUIDs are the same

### How to reproduce from Wagtail admin
1. Create a Streamfield block
2. Fill some data for the StreamBlock inside this block
3. Duplicate the Streamfield block

### Technical details

* Python version: any version
* Django version: 3.2.9
* Wagtail version: 2.15.1

### PR DESCRIPTION
**Pull request by jams2**
fixes #7712 (duplication of block ids when duplicating stream field blocks in page editor), supersedes https://github.com/wagtail/wagtail/pull/7713.

This implementation (based on @gasman and @jacobtoppm 's comments on https://github.com/wagtail/wagtail/pull/7713) adds `getDuplicatedState` methods to `BaseSequenceChild`, `BaseSequenceBlock` (inherited by `ListBlock` and `StreamChild`), `StreamChild`, and `StructBlock`.

`getDuplicatedState` generates new block ids for stream/list children (at all levels of nesting) when duplicating blocks. It is called in the `duplicate`/`duplicateBlock` methods of compound block types.

Tested manually that block duplication still works as expected in the page editor in Firefox and Chrome.

### CODE REVIEW

File: client/src/entrypoints/contrib/typed_table_block/typed_table_block.js [hunk 1]
```diff
@@ -466,30 +466,44 @@ export class TypedTableBlock {
...
-      })),
+      columns: this.getColumnState(),
       rows: this.rows.map((row) => ({
         values: row.blocks.map((block) => block.getValue()),
       })),
     };
     return value;
   }
 
+  getColumnState() {
```
Comment (ababic) [inline client/src/entrypoints/contrib/typed_table_block/typed_table_block.js:500]: Nice improvement here!`getColumnsState` (with an s) might be ever-so-slightly clearer though, since there are usually multiple columns

Comment (jams2) [reply client/src/entrypoints/contrib/typed_table_block/typed_table_block.js:500]: Good point!

Comment (ababic) [reply client/src/entrypoints/contrib/typed_table_block/typed_table_block.js:500]: Also, do we need a `getDuplicatedColumnState()`, or do columns not have ids?

File: client/src/components/StreamField/blocks/StructBlock.js [hunk 2]
```diff
@@ -111,6 +111,19 @@ export class StructBlock {
     return state;
   }
 
+  getDuplicatedState() {
+    const state = {};
+    // eslint-disable-next-line guard-for-in
+    for (const name in this.childBlocks) {
+      const block = this.childBlocks[name];
+      state[name] =
+        block.getDuplicatedState === undefined
```
Comment (ababic) [inline client/src/components/StreamField/blocks/StructBlock.js:120]: Looks like we are missing a test addition for this component?

**Review by ababic — CHANGES_REQUESTED** [review]
@jams2  Had a good comb through, and what is here looks really great (although, I must admin, some of this JS goes over my head!). 

One additional thing that occurred to me, though: Does the `ListBlock` component need updating too?

**Comment by jams2** [comment]
Thanks @ababic ! Going to mark this as a draft while I investigate the `ListBlock`

File: client/src/entrypoints/contrib/typed_table_block/typed_table_block.js (hunk 1 above)
Comment (jams2) [reply client/src/entrypoints/contrib/typed_table_block/typed_table_block.js:500]: If I'm not mistaken, we don't need to handle columns any differently. `TypedTableBlock.columns` is a list of objects that contain metadata for the column, including:
- the block definition of the "type" that can be inserted into rows in this column; and
- an integer ID, the index of the column, assigned when the column is created.

The IDs on the row items are generated in a similar fashion. These column and row IDs don't appear to have a unique constraint as they aren't used, e.g. as part of a contentpath for comments. The reason that we need special handling for rows is that the block type for a given column may be a complex type (e.g. a `StreamBlock`), which we would need to recurse into instances of, to make sure `StreamChild`, `ListChild`, etc. instances don't have duplicate IDs when duplicating a block.

However, this code is new to me so I'm happy to be corrected.

File: client/src/components/StreamField/blocks/StructBlock.js (hunk 2 above)
Comment (jams2) [reply client/src/components/StreamField/blocks/StructBlock.js:120]: This was sort of covered in StreamBlock.test.js but I've split them out to handle the block types more specifically in their corresponding modules.

File: client/src/entrypoints/contrib/typed_table_block/typed_table_block.js (hunk 1 above)
Comment (jams2) [reply client/src/entrypoints/contrib/typed_table_block/typed_table_block.js]: Regarding the name, I've gone with `getColumnStates` - that feels more natural to me.

Comment (ababic) [reply client/src/entrypoints/contrib/typed_table_block/typed_table_block.js]: Thanks for clarifying there @jams2. Happy with all of that :)

File: client/src/components/StreamField/blocks/StructBlock.js (hunk 2 above)
Comment (ababic) [reply client/src/components/StreamField/blocks/StructBlock.js:120]: 👍

**Review by ababic — APPROVED** [review]

**Review by kaedroho — APPROVED** [review]
This looks good to me, thanks!

And thanks @ababic for helping with review!
