### PR TITLE
Fix Collapse All button state reverting after switching tabs

### LINKED ISSUE #14020: Collapse All button state always reverts to Collapse All after changing tabs
### Issue summary

When changing tabs after selecting Collapse All on a tab, the button state always reverts to Collapse All (`aria-expanded="true"`) after switching tabs.

### Steps to reproduce

On a Wagtail page edit form, after load:

1. On Content, click Collapse All (button switches to Expand All) -> Click on Promote (button switches to Collapse All) -> Click back to Content, button remains on Collapse All.
2. On Promote, click Collapse All (button switches to Expand All) -> Click on Content (button switches to Collapse All) -> Click back to Promote, button remains on Collapse All.
3. Cick Collapse All on both tabs, toggle between tabs, button will remain on Collapse All.

### Additional information

The button state should reflect the tab state. Currently, it requires the user to click once to restore it to Expand All (without effect on the tab content), then click again for the expand to happen. 

### Can be reproduced

Yes, on a fresh Wagtail project

### Technical details

- Python version: 3.12.4
- Django version: 5.2.4
- Wagtail version: 7.3
- Browser version: Firefox 148, Chrome 146

### Working on this

If you would like to contribute to this issue, follow these steps:
- Confirm that the issue is reproducible, either on a fresh Wagtail project or the [bakerydemo](https://github.com/wagtail/bakerydemo).
- Once confirmed, view our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you're ready to start.

### PR DESCRIPTION
**Pull request by Raghaddahi**
Fixes #14020 

### Description

- `Minimap.tsx:` Updated state logic to store a map of tab states.
- `Minimap.tsx`: Deleted `useEffect` that was resetting the button. 
- `Minimap.test.tsx`: Added new tests for state persistence and defaults.

### Testing
tested it on bakeydemo

https://github.com/user-attachments/assets/3be5ff55-c8f6-45b0-8600-7f289b5e7dfc

### AI usage

Used Gemini to help write the code and the unit test files.

### CODE REVIEW

**Comment by Raghaddahi** [comment]
Note: I’ll add the remaining unit tests for the `Minimap.tsx` component in a separate PR if approved.

File: client/src/components/Minimap/Minimap.tsx [hunk 1]
```diff
@@ -120,7 +120,19 @@ const Minimap: React.FunctionComponent<MinimapProps> = ({
...
+
+  const panelsExpanded =
+    panelsExpandedByTab[anchorsContainer?.id ?? ''] ?? true;
+
+  const setPanelsExpanded = (value: boolean) => {
+    setPanelsExpandedByTab((prev) => ({
+      ...prev,
+      [anchorsContainer?.id ?? '']: value,
+    }));
+  };
```
Comment (laymonage) [inline client/src/components/Minimap/Minimap.tsx]: I think we can tidy it up a bit by using a variable for the container ID to avoid duplication and too much wrapping by prettier

```suggestion
  const containerId = anchorsContainer?.id ?? '';
  const panelsExpanded = panelsExpandedByTab[containerId] ?? true;
  const setPanelsExpanded = (value: boolean) => {
    setPanelsExpandedByTab((prev) => ({ ...prev, [containerId]: value }));
  };

```

**Review by laymonage — APPROVED** [review]
Works great, thanks for adding the tests as well!
