### PR TITLE
Set `aria-invalid` on StreamField widgets input when there is an error

### LINKED ISSUE #10300: Missing HTML widget attributes in StreamField widget rendering
### Issue Summary

Comparing the rendering of widgets in StreamField and outside, there are a number of attributes missing in the StreamField (Telepath?) variant. This is likely because we added those attributes to the FieldPanel’s [custom rendering](https://github.com/wagtail/wagtail/blob/main/wagtail/admin/panels/field_panel.py#L175) only, and didn’t replicate it for fields outside FieldPanel.

Specific attributes that are missing:

- [x] `required` for required fields. This likely predates any forms changes in v4.0
- [x] `aria-invalid="true"` for fields with errors
- [x] `aria-describedby` with an ID list pointing at any help text
- [ ] `aria-describedby` with an ID list pointing at any error messages

All `input type="text"` in StreamField seem to only ever render as:

```html
<input type="text" name="backstory-0-value-heading_text" id="backstory-0-value-heading_text">
```

Similarly a required `textarea` with an error message is:

```html
<textarea name="backstory-2-value-text" cols="40" rows="1" data-controller="w-autosize" class="w-field__autosize" id="backstory-2-value-text" style="overflow: hidden; overflow-wrap: break-word; text-align: start; height: 71px;"></textarea>
```

For comparison, here’s the markup for our page `title` field (excluding Stimulus attributes):

```html
<input type="text" name="title" placeholder="Page title*" maxlength="255" aria-invalid="true" aria-describedby="panel-child-content-child-title-helptext panel-child-content-child-title-errors" required="" id="id_title">
```

### Steps to Reproduce

1. Go to the homepage edit UI in the bakerydemo
2. In the Body field, add a new Embed block without setting a URL
3. Save draft
4. Inspect the URL input field for the block. It will be: `<input type="url" name="body-0-value" id="body-0-value">`

Instead, it should have the attributes mentioned above.

### PR DESCRIPTION
**Pull request by laymonage**
Fixes #10300.

Example with `EmbedBlock` as mentioned in the issue:

image

### CODE REVIEW

File: client/src/entrypoints/admin/telepath/widgets.js [hunk 1]
```diff
@@ -183,6 +191,18 @@ class BoundRadioSelect {
...
+    this.element
+      .querySelectorAll(`input[name="${this.name}"]`)
+      .forEach((input) => {
+        if (invalid) {
+          input.setAttribute('aria-invalid', 'true');
+        } else {
+          input.removeAttribute('aria-invalid');
+        }
+      });
+  }
```
Comment (laymonage) [inline client/src/entrypoints/admin/telepath/widgets.js:204]: I'm not 100% sure on this, I assume we want to set the `<aria-invalid>` on all the `<inputs>` for radio/checkbox inputs, since we can't really tell if the error was caused due to the user selecting a particular option or due to another reason e.g. selecting more than allowed.

File: client/src/components/StreamField/blocks/FieldBlock.js [hunk 2]
```diff
@@ -122,6 +122,12 @@ export class FieldBlock {
       .querySelectorAll('.error-message')
       .forEach((element) => element.remove());
 
+    // The widget knows exactly where the <input> is, so we let it handle the
+    // invalid state to e.g. set the aria-invalid attribute. Use optional
+    // chaining as custom widgets may not have implemented this method, or the
+    // widget itself may have failed to render in the first place.
+    this.widget?.setInvalid?.(!!error);
```
Comment (laymonage) [inline client/src/components/StreamField/blocks/FieldBlock.js:129]: I considered passing the `error` as-is and maybe naming the method `setError` instead coercing it to boolean and naming the method `setInvalid`, in case the widget wants to do something smart with the error messages.

However, it seems the error message is already handled by the `FieldBlock` rather than the widget (as seen in a few lines below this), so I opted to just keep it simple. Furthermore, there's already `setError` method in the `FieldBlock` itself, so I think the distinction helps.

File: client/src/entrypoints/admin/telepath/widgets.js (hunk 1 above)
Comment (thibaudcolas) [reply client/src/entrypoints/admin/telepath/widgets.js:204]: That’s a reasonable assumption and I think will be what’s most helpful to users in the absence of a `fieldset` / `radiogroup` around the elements.

**Review by thibaudcolas — APPROVED** [review]
Thank you @laymonage! All working well in latest Chrome / Safari / Firefox. There is a follow-up task needed to programmatically associate any error messages with widgets via `aria-describedby`, which I think might change this `setInvalid` API again, but I think it’s separate enough.

**Comment by lb-** [comment]
Awesome to see this in, amazing stuff @laymonage
