### PR TITLE
fixes 10764 -Inserting a new InlinePanel focus goes to wrong place

### LINKED ISSUE #10764: When inserting a new InlinePanel, focus goes to the wrong place.
### Issue Summary

When inserting a new InlinePanel, focus goes to the wrong place.

### Steps to Reproduce

1. Navigate to the edit view for a page with an inline panel.
2. Use keyboard navigation to focus the "add foos" button.
3. Hit enter.
4. Observe that:
    1. focus remains on the "add foos" button
    2. this is now at the end of the newly inserted InlinePanel / formset form element
    3. you must navigate back with shift+tab to get to the start of the newly inserted form

https://github.com/wagtail/wagtail/assets/1473980/b2a516d5-9316-48ad-be6f-471927967d29

This adds confusion and extra work for users relying on keyboard navigation or screen readers.

I would instead expect focus to move to the first field in the newly-inserted form.

### Technical details

-   Wagtail version: 5.0.2

### PR DESCRIPTION
**Pull request by faishal882**
Fixes #10764: When inserting a new InlinePanel, focus goes to the wrong place

## What i did?
 -> Added tabindex -1 in newly created inline form and removing tabindex attr from old forms, then scroll to first node of form

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

### CODE REVIEW

File: client/src/components/InlinePanel/index.js [hunk 1]
```diff
@@ -209,6 +209,28 @@ export class InlinePanel extends ExpandingFormset {
...
+    const inlineChildId = 'inline_child_' + prefix;
+    const formsArray = forms.toArray();
+
+    formsArray.forEach(function(node) {
+      const $node = $(node);
+
+      if ($node.attr('id') === inlineChildId) {
+        $node.attr('tabindex', -1);
+        $node.focus(function() {});
+        $node[0].scrollIntoView();
```
Comment (lb-) [inline client/src/components/InlinePanel/index.js:226]: Drive by comment. I have this run locally. 

However, this will need to call focus on the element, maybe with smooth scroll. 

Then it'll need to add an event listener for blur to remove the tab index. But only if it wasn't already there in the first place. 

Otherwise the tabIndex will stay when not required. 

Finally, below when you remove the tabIndex, that's probably not required - we should leave attributes as is if the node is not the one with the Id.

Comment (faishal882) [reply client/src/components/InlinePanel/index.js]: Thanks for your suggestions @lb-  since its my first contribution into wagatil

File: client/src/components/InlinePanel/index.js [hunk 2]
```diff
@@ -209,6 +209,36 @@ export class InlinePanel extends ExpandingFormset {
...
+      const $node = $(node);
+
+      if ($node.attr('id') === inlineChildId) {
+        if (!$node.attr('tabindex')) {
+          $node.attr('tabindex', -1);
+          $node[0].scrollIntoView({ behavior: 'smooth' });
+          $node.focus();
+          
+          // blur event listener to remove tabindex when it loses focus
+          $node.on('blur', function() {
```
Comment (lb-) [inline client/src/components/InlinePanel/index.js:231]:
```suggestion
          $node.one('blur', function() {
```

Let's ensure this listener does not stick around once run once. 

http://api.jquery.com/one/

File: client/src/components/InlinePanel/index.js [hunk 3]
```diff
@@ -209,6 +209,36 @@ export class InlinePanel extends ExpandingFormset {
     );
   }
 
+  addTabIndex(prefix) {
```
Comment (lb-) [inline client/src/components/InlinePanel/index.js:212]: Can we call this method `initialFocus`

```suggestion
  initialFocus(prefix) {
```

File: client/src/components/InlinePanel/index.js [hunk 4]
```diff
@@ -209,6 +209,36 @@ export class InlinePanel extends ExpandingFormset {
...
+    /*
+    add tabindex -1 into newly created form if attr not present and 
+    remove attr from old forms on blur event, if not present previously,
+    */
```
Comment (lb-) [inline client/src/components/InlinePanel/index.js:216]: Move this doc description to above the method and start it with `/**`. This will make it a JSDoc string.

File: client/src/components/InlinePanel/index.js [hunk 5]
```diff
@@ -226,6 +256,7 @@ export class InlinePanel extends ExpandingFormset {
       /__prefix__/g,
       formIndex,
     );
+    this.addTabIndex(newChildPrefix);
```
Comment (lb-) [inline client/src/components/InlinePanel/index.js:259]: Let's move this to the last thing in this method. After all the run Callbacks have fired. 

This way any Callbacks that add DOM or listeners can work before the focus code runs. 

Also, rename to `initialFocus`

**Review by lb- — CHANGES_REQUESTED** [review]
A few more bits of feedback, thanks for looking into this.

**Comment by faishal882** [comment]
hey @lb- i have made the changes as you have requested

File: client/src/components/InlinePanel/index.js [hunk 6]
```diff
@@ -243,5 +273,6 @@ export class InlinePanel extends ExpandingFormset {
       if (this.opts.onAdd) this.opts.onAdd(formIndex);
       if (this.opts.onInit) this.opts.onInit(formIndex);
     }
+    this.initialFocus(newChildPrefix);
```
Comment (lb-) [inline client/src/components/InlinePanel/index.js:276]: Let's keep this simple by passing in the selected INNER container as a jQuery node to this function. The current code flow is a bit convoluted and we can assume the exact ID that we want to target instead of going through each node and matching based on an ID.



```suggestion
    this.initialFocus($(`#inline_child_${newChildPrefix}-panel-content`));
```

Note that this 

Screenshot 2023-09-08 at 8 17 53 am

Screenshot 2023-09-08 at 8 17 37 am

File: client/src/components/InlinePanel/index.js [hunk 7]
```diff
@@ -208,6 +208,36 @@ export class InlinePanel extends ExpandingFormset {
...
+          $node.one('blur', () => {
+            if ($node.attr('tabindex') === '-1') {
+              $node.removeAttr('tabindex');
+            }
+          });
+        }
+      }
+    });
+  }
+
```
Comment (lb-) [inline client/src/components/InlinePanel/index.js:241]: This is a good start but as per comment below, we are doing a lot of 'work' here that we do not need to do.

1. No need to go through each form that is not disabled, instead we can just pass in a selected node via known ID structure.
2. Also, the code here is now NOT scrolling if tabIndex is already set, this is not what we want to do, we want to always scroll/focus but only set/remove the tabIndex if not already on the element.
3. Finally, the JSDoc needs a bit of formatting work and should include a note about the focusing now.

```suggestion  /**
   * Add tabindex -1 into newly created form if attr not present and
   * remove attr from old forms on blur event, if not present previously.
   * Always scroll and then focus on the element.
   */
  initialFocus($node) {
    if (!$node || !$node.length) return;

    if (!$node.attr('tabindex')) {
      $node.attr('tabindex', -1);
      // blur event listener to remove tabindex when it loses focus
      $node.one('blur', () => {
        if ($node.attr('tabindex') === '-1') {
          $node.removeAttr('tabindex');
        }
      });
    }

    $node[0].scrollIntoView({ behavior: 'smooth' });
    $node.focus();
  }
```

**Review by lb- — CHANGES_REQUESTED** [review]
@faishal882  looking good, works ok but upon using this I think it's best to focus on the inner container, just outside of the form fields.

When using the keyboard only, this means that the next focusable target will likely be the first field instead of needing to tab five times to get to the field. Panel link, Panel collapse button, up, down, delete... then field.

I know the original issue is about scrolling, but we want to make this work much better for keyboard only users.

With the recommended changes, observe the behaviour for screen readers and keyboard only is hopefully much better.


https://github.com/wagtail/wagtail/assets/1396140/6f0ed77f-eb3a-4d0f-850b-edc77b2a62f2

**Comment by faishal882** [comment]
thanks for suggestion @lb-  
apologies for unnecessary comments

**Review by lb- — APPROVED** [review]
This is working great now, thank you for working through the feedback.

**Comment by lb-** [comment]
Just rebased/squashed, will merge in after a few CI checks run.

Thanks for making your first contribution to Wagtail @faishal882 !

**Comment by lb-** [comment]
@faishal882 no problems. Thanks for following through with it all. 

If you're keen on another, there is an issue that is a nice enhancement and it will be need a code change in pretty much the same area of code. 

https://github.com/wagtail/wagtail/issues/9105

This enhancement will make it easier for JS customisations to hook into the events of InlinePanel.

**Comment by faishal882** [comment]
Thanks @lb-  i will look into the issue
